// AUTO-GENERATED by scripts/sync-contract-abis.mjs from Foundry artifacts.
// Do not edit by hand; run `pnpm contracts:sync` after changing contracts.

export const rwagmiEthDevBuyAbi = [
  {
    "type": "constructor",
    "inputs": [
      {
        "name": "launcher_",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "poolManager_",
        "type": "address",
        "internalType": "contract IPoolManager"
      },
      {
        "name": "weth_",
        "type": "address",
        "internalType": "contract IWETH9"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "receive",
    "stateMutability": "payable"
  },
  {
    "type": "function",
    "name": "launcher",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "poolManager",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract IPoolManager"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "receiveTokens",
    "inputs": [
      {
        "name": "config",
        "type": "tuple",
        "internalType": "struct IRwagmiB20Launcher.LaunchConfig",
        "components": [
          {
            "name": "b20Config",
            "type": "tuple",
            "internalType": "struct IRwagmiB20Launcher.B20Config",
            "components": [
              {
                "name": "variant",
                "type": "uint8",
                "internalType": "enum IRwagmiB20Launcher.B20Variant"
              },
              {
                "name": "salt",
                "type": "bytes32",
                "internalType": "bytes32"
              },
              {
                "name": "params",
                "type": "bytes",
                "internalType": "bytes"
              },
              {
                "name": "initCalls",
                "type": "bytes[]",
                "internalType": "bytes[]"
              },
              {
                "name": "name",
                "type": "string",
                "internalType": "string"
              },
              {
                "name": "symbol",
                "type": "string",
                "internalType": "string"
              },
              {
                "name": "decimals",
                "type": "uint8",
                "internalType": "uint8"
              },
              {
                "name": "initialAdmin",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "originatingChainId",
                "type": "uint256",
                "internalType": "uint256"
              }
            ]
          },
          {
            "name": "poolConfig",
            "type": "tuple",
            "internalType": "struct IRwagmiB20Launcher.PoolConfig",
            "components": [
              {
                "name": "hook",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "pairedToken",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "lpFee",
                "type": "uint24",
                "internalType": "uint24"
              },
              {
                "name": "tickIfToken0IsB20",
                "type": "int24",
                "internalType": "int24"
              },
              {
                "name": "tickSpacing",
                "type": "int24",
                "internalType": "int24"
              },
              {
                "name": "poolData",
                "type": "bytes",
                "internalType": "bytes"
              }
            ]
          },
          {
            "name": "lockerConfig",
            "type": "tuple",
            "internalType": "struct IRwagmiB20Launcher.LockerConfig",
            "components": [
              {
                "name": "locker",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "rewardAdmins",
                "type": "address[]",
                "internalType": "address[]"
              },
              {
                "name": "rewardRecipients",
                "type": "address[]",
                "internalType": "address[]"
              },
              {
                "name": "rewardBps",
                "type": "uint16[]",
                "internalType": "uint16[]"
              },
              {
                "name": "tickLower",
                "type": "int24[]",
                "internalType": "int24[]"
              },
              {
                "name": "tickUpper",
                "type": "int24[]",
                "internalType": "int24[]"
              },
              {
                "name": "positionBps",
                "type": "uint16[]",
                "internalType": "uint16[]"
              },
              {
                "name": "lockerData",
                "type": "bytes",
                "internalType": "bytes"
              }
            ]
          },
          {
            "name": "mevModuleConfig",
            "type": "tuple",
            "internalType": "struct IRwagmiB20Launcher.MevModuleConfig",
            "components": [
              {
                "name": "mevModule",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "mevModuleData",
                "type": "bytes",
                "internalType": "bytes"
              }
            ]
          },
          {
            "name": "extensionConfigs",
            "type": "tuple[]",
            "internalType": "struct IRwagmiB20Launcher.ExtensionConfig[]",
            "components": [
              {
                "name": "extension",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "msgValue",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "extensionBps",
                "type": "uint16",
                "internalType": "uint16"
              },
              {
                "name": "extensionData",
                "type": "bytes",
                "internalType": "bytes"
              }
            ]
          },
          {
            "name": "poolSupply",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "adminMode",
            "type": "uint8",
            "internalType": "enum IRwagmiB20Launcher.AdminMode"
          }
        ]
      },
      {
        "name": "poolKey",
        "type": "tuple",
        "internalType": "struct PoolKey",
        "components": [
          {
            "name": "currency0",
            "type": "address",
            "internalType": "Currency"
          },
          {
            "name": "currency1",
            "type": "address",
            "internalType": "Currency"
          },
          {
            "name": "fee",
            "type": "uint24",
            "internalType": "uint24"
          },
          {
            "name": "tickSpacing",
            "type": "int24",
            "internalType": "int24"
          },
          {
            "name": "hooks",
            "type": "address",
            "internalType": "contract IHooks"
          }
        ]
      },
      {
        "name": "token",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "extensionTokenSupply",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "extensionIndex",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [],
    "stateMutability": "payable"
  },
  {
    "type": "function",
    "name": "supportsInterface",
    "inputs": [
      {
        "name": "interfaceId",
        "type": "bytes4",
        "internalType": "bytes4"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "pure"
  },
  {
    "type": "function",
    "name": "unlockCallback",
    "inputs": [
      {
        "name": "data",
        "type": "bytes",
        "internalType": "bytes"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bytes",
        "internalType": "bytes"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "weth",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract IWETH9"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "error",
    "name": "AddressEmptyCode",
    "inputs": [
      {
        "name": "target",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "AddressInsufficientBalance",
    "inputs": [
      {
        "name": "account",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "DevBuyRequiresEth",
    "inputs": []
  },
  {
    "type": "error",
    "name": "DevBuySlippage",
    "inputs": [
      {
        "name": "minimumOut",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "actualOut",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "ExtensionSupplyMustBeZero",
    "inputs": []
  },
  {
    "type": "error",
    "name": "FailedInnerCall",
    "inputs": []
  },
  {
    "type": "error",
    "name": "OnlyLauncher",
    "inputs": []
  },
  {
    "type": "error",
    "name": "OnlyPoolManager",
    "inputs": []
  },
  {
    "type": "error",
    "name": "PairedTokenMustBeWeth",
    "inputs": []
  },
  {
    "type": "error",
    "name": "SafeCastOverflowedIntToUint",
    "inputs": [
      {
        "name": "value",
        "type": "int256",
        "internalType": "int256"
      }
    ]
  },
  {
    "type": "error",
    "name": "SafeCastOverflowedUintToInt",
    "inputs": [
      {
        "name": "value",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "SafeERC20FailedOperation",
    "inputs": [
      {
        "name": "token",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "SettlementMismatch",
    "inputs": [
      {
        "name": "expected",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "actual",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "UnexpectedPairedTokenPoolKey",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ZeroAddress",
    "inputs": []
  }
] as const
